<?php

?><html>
<head>
	<title>Wiki for Bitcoin</title>
</head>
<body>

<a href=''>Home</a> | <a href=''>Edit this page</a> | <a href=''>Discuss</a> | <a href=''>History</a>

<h1>Wiki for Bitcoin</h1>


<?=$vars['name']?>

<p>Hello! You can edit this wiki, for 1 satoshi. No login required.</p>


<hr>
Powered by <a href='https://github.com/thorie7912/lnwiki'>lnwiki</a> v0.1.0 | <a href='/index'>All pages</a>

</body>
</html>
